# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db3b61ddd0ddfc30c62d3ca7da1a884525bd847f938b95cb1093acd819502e71f3434900f97915e6c32648c427c20344456bbf1fa010ad5315a1b12b38d09d39

test:
  secret_key_base: aa7d69a807e9a1d5ca75d51d05ecadfcc824e44e9f6fccd0706473df739b9ec668e56bdde84c9fb0c794f426ea5d275c4dc30462bafb78dc8e3b29b03b59d52c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
